/var/log/xray/*.log {
    daily
    rotate 30
    maxsize 100M
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    create 0640 root root
}

/var/log/xray-geodata-updater/*.log {
    weekly
    rotate 8
    maxsize 10M
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    create 0640 root root
}
